# Generated by Django 3.2 on 2022-01-07 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baking_app', '0002_bake_remove_step_blog_delete_blog_step_bake'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
